/**
 * REPORTS: GENERATED FILES
 *
 * TABLE: report_file
 *
 * PURPOSE:
 * - List outputs produced from report_snapshot generation:
 *   - CSV, PDF, XLSX, JSON bundles
 * - Provide download/open actions (presigned URL later)
 *
 * EXPECTED FIELDS (typical):
 * - report_file_id, snapshot_id, file_name, file_type
 * - storage_key (S3), size_bytes, created_at
 * - checksum/signature (optional), expires_at (optional)
 */

import { useAuth } from "../../auth/useAuth";
import { Badge, Card, Note, ReportsShell, Table } from "./shared/reports-ui";

export default function ReportFilesPage() {
  const { tenant, dashboardMode } = useAuth();

  const rows = [
    [
      "Election Results • County Summary",
      "Presidential General 2029",
      "CSV",
      "2.3 MB",
      dashboardMode === "NEC" ? "NEC" : tenant?.orgName ?? "Tenant Org",
      "10m ago",
      "report_file",
      fileActions(),
    ],
    [
      "Integrity • Discrepancy List",
      "Presidential General 2029",
      "CSV",
      "540 KB",
      dashboardMode === "NEC" ? "NEC" : tenant?.orgName ?? "Tenant Org",
      "30m ago",
      "report_file",
      fileActions(),
    ],
    [
      "Submissions • Verified Snapshot",
      "Presidential General 2029",
      "XLSX",
      "6.1 MB",
      tenant?.orgName ?? "Tenant Org",
      "2h ago",
      "report_file",
      fileActions(),
    ],
  ];

  return (
    <ReportsShell
      title="Reports • Generated Files"
      subtitle="Download outputs generated by the report queue. Later uses secure presigned URLs."
      right={<Badge>{dashboardMode}</Badge>}
    >
      <Card
        title="Files"
        right={
          <div className="flex flex-wrap gap-2">
            <button className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-semibold hover:bg-slate-50">
              Search (later)
            </button>
            <button className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-semibold hover:bg-slate-50">
              Filters (later)
            </button>
          </div>
        }
      >
        <Table
          columns={[
            "Report",
            "Election",
            "Type",
            "Size",
            "Owner",
            "Created",
            "Source",
            "Actions",
          ]}
          rows={rows}
        />

        <div className="mt-3 grid grid-cols-1 gap-3 lg:grid-cols-2">
          <Note
            title="Later behavior (security)"
            bullets={[
              "Downloads use presigned URLs (S3) with expiry.",
              "Tenants only see their org-generated files unless NEC/System policy allows broader access.",
              "Auditable downloads (audit_log / audit_ledger if sensitive).",
            ]}
          />
          <Note
            title="Integration points"
            bullets={[
              "Results pages: Export → create report_snapshot → generate report_file.",
              "Operations queues: Export → snapshot + file.",
              "NEC Workflow: Official published exports can be controlled by public flag.",
            ]}
          />
        </div>
      </Card>
    </ReportsShell>
  );
}

function fileActions() {
  return (
    <div className="flex gap-2">
      <button className="rounded-xl border border-slate-200 bg-white px-2 py-1 text-xs font-bold hover:bg-slate-50">
        Open
      </button>
      <button className="rounded-xl border border-slate-200 bg-white px-2 py-1 text-xs font-bold hover:bg-slate-50">
        Download
      </button>
    </div>
  );
}
