package election.ems_backend.enums;

public enum AnomalyKind {
    BALLOT_MATH_MISMATCH,
    OVER_CAPACITY_TURNOUT,
    DUPLICATE_VERIFIED_ATTEMPT,
    LATE_SUBMISSION,
    GEO_OUT_OF_BOUNDS,
    OCR_MISMATCH,
    NETWORK_RETRY_SPIKE,
    BALLOT_STUFFING,
    VOTER_INTIMIDATION,
    EQUIPMENT_FAILURE,
    TALLY_MISMATCH,
    NETWORK_OUTAGE,
    OTHER
}
